version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/project